### PR TITLE
Add more typedefs

### PR DESCRIPTION
**Pull request by VictorLamoine**
Using Isometries rather than Affines makes more sense when talking about robot poses.
See for example: https://github.com/ros/geometry/issues/101

### CODE REVIEW

**Comment by VictorLamoine** [comment]
@wjwwood or @dirk-thomas, any comments?

**Comment by v4hn** [comment]
Looks good to me. It would be nice to have these typedefs available.

**Comment by VictorLamoine** [comment]
Would someone be so kind as to merge? :1st_place_medal:

**Comment by wjwwood** [comment]
I'm not sure who's supposed to be maintaining this. I guess it was Ioan and then Jackie. @clalancette and @sloretz I don't suppose either of you guys would be interested in picking this up? It's in the same vein as `robot_model` and `robot_state_publisher`.

**Comment by sloretz** [comment]
I'm happy to pick it up

**Comment by clalancette** [comment]
Shane, do you want to do joint maintenance on it, or just go solo on this one?  I'm fine either way, just let me know.

**Pull request merged**
